services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  generator:
    image: golang:1.17-alpine
    working_dir: /app
    command: ["go", "run", "internal/cmd/generator/main.go"]
    volumes:
      - ".:/app"
    profiles:
      - manual

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d"
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - .env:/app/.env
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      database:
        condition: service_healthy
      nats:
        condition: service_started
    environment:
      - SERVICE_NAME=casino-subscriber
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
      - EXCHANGE_RATE_API_URL=${EXCHANGE_RATE_API_URL}
      - EXCHANGE_RATE_CACHE_DURATION=${EXCHANGE_RATE_CACHE_DURATION}
      - EXCHANGE_RATE_SOURCE_CURRENCY=${EXCHANGE_RATE_SOURCE_CURRENCY}
      - NATS_URL=${NATS_URL}

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=remote-write-receiver'
    depends_on:
      app:
        condition: service_healthy
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    networks:
      - default

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["publisher"]
    working_dir: /app
    volumes:
      - .:/app
      - .env:/app/.env
    depends_on:
      nats:
        condition: service_started
    environment:
      - SERVICE_NAME=casino-publisher
      - NATS_URL=${NATS_URL}

volumes:
  postgres_data:

networks:
  default:
    name: casino-network
